openapi: 3.0.0
info:
  version: 0.0.1
  title: GHQ Master Data API
  description: >-
    Read-only API to load gaming master data.
    Also includes default Spring Boot Actuator endpoints not documented here.
  license:
    name: MIT License
servers:
  - url: /api/v1
    description: GHQ Master Data Server
paths:
  /countries:
    get:
      summary: List all countries
      operationId: listCountries
      x-spring-paginated: true
      tags:
        - countries
      responses:
        '200':
          description: A page of countries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryPage'
  /countries/{countryId}:
    get:
      summary: Get a country by ID
      operationId: getCountry
      tags:
        - countries
      parameters:
        - name: countryId
          in: path
          required: true
          description: The ID of the country to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A country object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
  /developers:
    get:
      summary: List all developers
      operationId: listDevelopers
      x-spring-paginated: true
      tags:
        - developers
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeveloperPage'
  /developers/{developerId}:
    get:
      summary: Get a developer by ID
      operationId: getDeveloper
      tags:
        - developers
      parameters:
        - name: developerId
          in: path
          required: true
          description: The ID of the developer to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A country object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
  /dlcs:
    get:
      summary: List all dlcs
      operationId: listDlcs
      x-spring-paginated: true
      tags:
        - dlcs
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeveloperPage'
  /dlcs/{dlcId}:
    get:
      summary: Get a DLC by ID
      operationId: getDLC
      tags:
        - dlcs
      parameters:
        - name: dlcId
          in: path
          required: true
          description: The ID of the DLC to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A DLC object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DLC'
  /games:
    get:
      summary: List all games
      operationId: listGames
      x-spring-paginated: true
      tags:
        - games
      parameters:
        - in: query
          name: developerId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamePage'
  /games/{gameId}:
    get:
      summary: Get a game by ID
      operationId: getGame
      tags:
        - games
      parameters:
        - name: gameId
          in: path
          required: true
          description: The ID of the game to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /genres:
    get:
      summary: List all genres
      operationId: listGenres
      x-spring-paginated: true
      tags:
        - genres
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamePage'
  /genres/{genreId}:
    get:
      summary: Get a genre by ID
      operationId: getGenre
      tags:
        - genres
      parameters:
        - name: genreId
          in: path
          required: true
          description: The ID of the genre to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A genre object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
  /platforms:
    get:
      summary: List all platforms
      operationId: listPlatforms
      x-spring-paginated: true
      tags:
        - platforms
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformPage'
  /platforms/{platformId}:
    get:
      summary: Get a platform by ID
      operationId: getPlatform
      tags:
        - platforms
      parameters:
        - name: platformId
          in: path
          required: true
          description: The ID of the platform to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A platform object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
  /releases:
    get:
      summary: List all releases
      operationId: listReleases
      x-spring-paginated: true
      tags:
        - releases
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReleasePage'
  /releases/{releaseId}:
    get:
      summary: Get a release by ID
      operationId: getReleases
      tags:
        - releases
      parameters:
        - name: releaseId
          in: path
          required: true
          description: The ID of the release to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A release object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
  /screenshots:
    get:
      summary: List all screenshots
      operationId: listScreenshots
      x-spring-paginated: true
      tags:
        - screenshots
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenshotPage'
  /screenshots/{screenshotId}:
    get:
      summary: Get a screenshot by ID
      operationId: getScreenshot
      tags:
        - screenshots
      parameters:
        - name: screenshotId
          in: path
          required: true
          description: The ID of the screenshot to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A screenshot object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Screenshot'
  /game-tags:
    get:
      summary: List all game tags
      operationId: listGameTags
      x-spring-paginated: true
      tags:
        - gameTags
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameTagPage'
  /game-tags/{gameTagId}:
    get:
      summary: Get a game tag by ID
      operationId: getGameTag
      tags:
        - gameTags
      parameters:
        - name: gameTagId
          in: path
          required: true
          description: The ID of the game tag to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A game tag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameTag'
  /videos:
    get:
      summary: List all videos
      operationId: listVideos
      x-spring-paginated: true
      tags:
        - videos
      parameters:
        - in: query
          name: gameId
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
      responses:
        '200':
          description: A
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoPage'
  /videos/{videoId}:
    get:
      summary: Get a video by ID
      operationId: getVideo
      tags:
        - videos
      parameters:
        - name: videoId
          in: path
          required: true
          description: The ID of the video to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A video object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
components:
  parameters:
    fromParam:
      in: query
      name: form
      schema:
        type: string
        format: date
      description: Filter results equals or after this date.
    toParam:
      in: query
      name: to
      schema:
        type: string
        format: date
      description: Filter results equals or before this date.
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
          format: int64
        alpha2:
          type: string
          maxLength: 2
        alpha3:
          type: string
          maxLength: 3
    CountryPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Country'
    Developer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: integer
          format: int64
    DeveloperPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Developer'
    DLC:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gameId:
          type: integer
          format: int64
          description: The ID of the game this DLC belongs to.
    DLCPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/DLC'
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        developerId:
          $ref: '#/components/schemas/Developer/properties/id'
    GamePage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Game'
    Genre:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    GenrePage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Genre'
    Platform:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        manufacturer:
          type: string
    PlatformPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Platform'
    Release:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        gameId:
          $ref: '#/components/schemas/Game/properties/id'
        dlcId:
          $ref: '#/components/schemas/DLC/properties/id'
        countryId:
          $ref: '#/components/schemas/Country/properties/id'
    ReleasePage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Release'
    Screenshot:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
        gameId:
          $ref: '#/components/schemas/Game/properties/id'
        dlcId:
          $ref: '#/components/schemas/DLC/properties/id'
    ScreenshotPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Screenshot'
    GameTag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gameId:
          $ref: '#/components/schemas/Game/properties/id'
    GameTagPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/GameTag'
    Video:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
        gameId:
          $ref: '#/components/schemas/Game/properties/id'
        dlcId:
          $ref: '#/components/schemas/DLC/properties/id'
    VideoPage:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Video'
    PaginationResponse:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          default: 0
        totalPages:
          type: integer
          default: 0
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        pageable:
          $ref: '#/components/schemas/Pageable'
        numberOfElements:
          type: integer
        size:
          type: integer
        empty:
          type: boolean
        content:
          type: array
          items: { }
    Pageable:
      type: object
      format: pageable
      properties:
        page:
          type: integer
          minimum: 0
        size:
          type: integer
          minimum: 1
        sort:
          type: array
          items:
            type: string
    Sort:
      type: object
      format: sort
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean